stages:
  - build
  - test

variables:
  DOTNET_VERSION: "6.0"
  BUILD_OUTPUT: "$CI_PROJECT_DIR/build"
  PACKAGE_OUTPUT: "$CI_PROJECT_DIR/pkg"
  SOLUTION_NAME: "Bsh"
  GTFO_DEP_URL: "https://git.takina.io/api/v4/projects/6/packages/generic/gtfobepindep/2025.10.18/GTFOBepInDep.zip"
  GTFO_DEP_DIR: "$CI_PROJECT_DIR/GTFOBepInDep"

before_script:
  - echo "Using .NET version $DOTNET_VERSION"
  - export DOTNET_ROOT=$(dirname $(which dotnet))
  - dotnet --version

build:
  stage: build
  tags:
    - dotnet
  image: mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - apt-get update && apt-get install -y tree zip unzip python3 python3-pip python-is-python3
  script:
    - echo "Downloading GTFO dependencies..."
    - wget -O GTFOBepInDep.zip "$GTFO_DEP_URL"
    - unzip -o GTFOBepInDep.zip -d "$CI_PROJECT_DIR"
#    - ls -R "$GTFO_DEP_DIR"
    - dotnet restore
    - echo "Building project..."
    - dotnet build --configuration Release --output $BUILD_OUTPUT
    - cd $PACKAGE_OUTPUT
    - zip -r $CI_PROJECT_DIR/$SOLUTION_NAME.zip ./*
  artifacts:
    paths:
      - $SOLUTION_NAME.zip

test:
  stage: test
  tags:
    - dotnet
  image: mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - apt-get update && apt-get install -y unzip
  script:
    - echo "Running tests..."
    - dotnet restore
    - dotnet test --configuration Release
#    artifacts:
#        paths:
#            - TestResults/
