<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Bsh.Tests</AssemblyName>
        <RootNamespace>Bsh.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\BashTerm\BashTerm.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MSTest" Version="3.7.3"/>
    </ItemGroup>
</Project>
