namespace BashTerm;

public enum TermCmd : byte {
	None,
	Help,
	Commands,
	Cls,
	Exit,
	Open,
	Close,
	Activate,
	Deactivate,
	EmptyLine,
	InvalidCommand,
	DownloadData,
	ViewSecurityLog,
	Override,
	DisableAlarm,
	Locate,
	ActivateBeacon,
	Find,
	ShowList,
	Query,
	Ping,
	ReactorStartup,
	ReactorVerify,
	ReactorShutdown,
	WardenObjectiveSpecialCommand,
	TerminalUplinkConnect,
	TerminalUplinkVerify,
	TerminalUplinkConfirm,
	ListLogs,
	ReadLog,
	TryUnlockingTerminal,
	WardenObjectiveGatherCommand,
	TerminalCorruptedUplinkConnect,
	TerminalCorruptedUplinkVerify,
	UsedCommand,
	UniqueCommand1,
	UniqueCommand2,
	UniqueCommand3,
	UniqueCommand4,
	UniqueCommand5,
	Info,

	// Custom Cmds
	Raw,
}
